version: "3.1"

services:
  web:
    build: .
    container_name: web
    depends_on:
      - db
    env_file:
      - .env
    command: bash -c "
      alembic upgrade head &&
      gunicorn app:factory --bind 0.0.0.0:8000 --worker-class aiohttp.GunicornWebWorker --reload"
    expose:
      - "8000"
    volumes:
      - ./src:/src
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
